[package]
name = "readaby"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pretty_env_logger = "0.5.0"
readability = "0.2.0"
clap = {version = "4.4.2", features = ["derive"] }
log = "0.4.20"
